version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - src/.env
    ports:
      - "5432:5432"
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8002
    volumes:
      - ./src:/app/src
    ports:
      - "8002:8002"
    depends_on:
      - db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_worker
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
    depends_on:
      - web
      - redis
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
volumes:
  db:
  elasticsearch-data: