# Generated by Django 4.2.3 on 2023-11-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_review_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemInCart',
            new_name='Item',
        ),
    ]
