# Generated by Django 4.2.3 on 2023-11-16 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_itemincart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2023, 11, 16, 11, 51, 53, 41117, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
